{% set version = "2.0.3" %}

package:
  name: gitdb2
  version: {{ version }}

source:
  fn: gitdb2-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/gitdb2/gitdb2-{{ version }}.tar.gz
  sha256: b60e29d4533e5e25bb50b7678bbc187c8f6bcff1344b4f293b2ba55c85795f09

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - smmap2

test:
  imports:
    - gitdb
    - gitdb.db

about:
  home: https://github.com/gitpython-developers/gitdb
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A pure-Python git object database'

extra:
  recipe-maintainers:
    - ngoldbaum
    - ocefpaf
