{% set version = "3.0.0" %}

package:
  name: gitdb2
  version: {{ version }}

source:
  fn: gitdb2-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/gitdb2/gitdb2-{{ version }}.tar.gz
  sha256: 51380b9d8b977b42ac9fc3a8e17af90a56ffc573ca9c6b79f99033b04f29f457

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - smmap2

test:
  imports:
    - gitdb
    - gitdb.db

about:
  home: https://github.com/gitpython-developers/gitdb
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A pure-Python git object database'

extra:
  recipe-maintainers:
    - ngoldbaum
    - ocefpaf
