{% set version = "2.0.6" %}

package:
  name: gitdb2
  version: {{ version }}

source:
  fn: gitdb2-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/gitdb2/gitdb2-{{ version }}.tar.gz
  sha256: 1b6df1433567a51a4a9c1a5a0de977aa351a405cc56d7d35f3388bad1f630350

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - smmap2 >=2.0.0

test:
  imports:
    - gitdb
    - gitdb.db

about:
  home: https://github.com/gitpython-developers/gitdb
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A pure-Python git object database'

extra:
  recipe-maintainers:
    - ngoldbaum
    - ocefpaf
