travis:
  secure:
    BINSTAR_TOKEN: kWzmlN6ixgkYcw03KYuW02fjOPyOIV/HbdJic3s1MfVHH9G4bk48BfGrx3EFo5TUC/DoWNbp60E9bmVvD7lFK8i93/+llSMQ/MxmSkL4ayrN6aNKQRDk/e73EO1AisFuvE/yMQemikCfUOz59OKCig0ey57oQOU2aZ20y8a3FEdECn5xev67zTdTN/4BzIKF6qXTfcBuxeJ+GNWmSacJzV2JlzVWMf7Dxh1RpCGl9DGuq+7zyDkJzrA0MExicaUXGd8wMzZTy/ASB+Ug4QoudaWdjuvSapMEZnQ+M+Y55y2/8b7tCbroCk7Ilslc2ZiEu0xQ1FckHyyWrtWIcx0Mke5aN9Du8PMMP77e41VPGMQMnmvzucNNtsbyg+vyzPUV+QLvZ8H8pwNrchgJj/yOzC6fmHTif/ekE+qy9gvF5No/+yA/pWohogt3GUOb7TsioNPIlTkRO/agref2oDnJp95WU1/W931Dvci2UKSik6w3vO1OuNiHoN4hCqT78bm7hy02DHnJN6svJh8UUk0JvHdAMxIMcYSWg11FaWyR+cIIp17Otyeb94GqjCE7hrJZ0xAesT6mBzblYLngwbdHfcKGkkLoVQ/DUxIcJxwPH+t2WvQ5yPZmUg4BNMXj1vxt7im/YgJEgKL3il18ClVsjlDr33t2n1YFA7DBojDrQGs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
