travis:
  secure:
    BINSTAR_TOKEN: PvgYlymWc014rE+pnxnDKCcRfCF4O8ldhPusQUpActRJ1rnEkaUE2BlwqQ6ytxL5mFbgM+7xotyBqZJhi1evV9MHX6EnK/V8JNgZXuXC8x1vxfCbwvQRHEdiImLjEhkCdJWL9GGl1vLwngl0up3Y0vWEpoXdM26TdZMkmluwbd7pY74HgGYaFmyZaTS8ljbjvaGGvdH/eF5XjISSucek0uc7Ej6zqoMbriRdoPo44JxodOIWL2BtdtSUylF6ab7eyZIMGuVLCVFtLKkP7o+zweDwK3GOGM9VKcQ0SerowwHMu6MUTa/YhQSGIRj0vAK1iKEQTHqZqFIzBREa38Uck7mT18Ly/nze8i1iRvVowGeajJfcOuaaqqHANb5azvudoMBHvlGT7l4lWetjeZsB5fZCqczj35ZUCVVbrIfXZhJNGyGXMEPz6bztMdx86NN0ldAsK04tWVd6UFnCWJ5fs7mzvwAj3zfG62ldfk2jDy+3kIfbdZrGK+wzT/rJWkViV4YZRpfs4E+7MlgbzxOB94IQ9twvJWBAUGM7GNAvO5BuSeQ6cHOP25MhyBBI7ELpZEu7aIZUKgwqWBDGEPvKP7cEhih89XUGvz31/Wjr6XLfo448kt7ZDiLDve+oAKZsu2zozJ/Md/JNuCC1kmbdKecDKx4JwucC72Tv6cX7GIo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
