travis:
  secure:
    BINSTAR_TOKEN: agiTyMhGWrqqgvmrv/henIOjses75B1vO2Y49Z15xF3EaCuBC1qEL16mWHftv3AjAGaXjKBTLfFtS9xQBRoJezKeN1sO+GO1YKzQ2PWwNMA1CdQIScZo0IzKijLbpg3D3RwOj2r2Jllwr4JZGnLPyhmxw5IW3FAsVkQTtN1g1DgUKIB+d/csG6K8/uJPtzO8dyw8iPZeskn0S6d4a5T2Amx6nLA1guDjsjsQu/GS13XdzINvRyCHamejaLGKxCJ1BcLzIgXZv9jkbcbEtAcYXE+LetVVlDkJ8NBK3dYUAOFL0LZ5YzAKxqzHVnipdpsAMCdVX61rNlvF3tOdCRzHxup3JjdQEpiv+8du/TWgatmVN7YYF40Lc71LvrsAicQwKH4nv6QWrjoZmjVSIZ89nprgBcLxoYe358cpeUxvPtip2sIFhYlqVXgYWdHP2+YOykXj0GzgbwZXcnQub5Z2/WzO29iIGlcCf/ltTfx73yvVAEJfiZUu0e1cU8g8ycik1H9gpC3+ZWzATqBhQ7KxS284ac6NWjAmZYv6R+YdMi+tL9y7fAdVvpkfmJ/elWMXC6T0Fg8WwjlU3klESJfCwGETGzLqGh5UeBs3CpC9vUc0rO5YcrEgKpFMpBsF8iDr2TH6+etNmnNRoWD6l/qUfM+neCJ8k8Fv+hYQ3Ax/ugc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
